site_name: MkDocs
site_url: https://www.mkdocs.org
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    feature:
        tabs: true

nav:
    - 主页: index.md
    - 用户指南:
          - 编辑文档: user-guide/writing-your-docs.md
          - 化妆文档: user-guide/styling-your-docs.md
          - 配置: user-guide/configuration.md
          - 部署文档: user-guide/deploying-your-docs.md
          - 自定义主题: user-guide/custom-themes.md
          - 插件: user-guide/plugins.md
    - 关于:
          - 发行说明: about/release-notes.md
          - 贡献: about/contributing.md
          - 证书: about/license.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
          permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
          user: mkdocs
          repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
google_analytics: ["UA-27795084-5", "mkdocs.org"]

plugins:
    - search
